# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-06 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190528_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='phone',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='login_time',
            field=models.CharField(max_length=20, null=True, verbose_name='登陆时间'),
        ),
    ]
