# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-11 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20190706_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmpuserinfo',
            name='username',
            field=models.CharField(max_length=255, verbose_name='用户名'),
        ),
    ]
